language: python
python:
  - 3.6
sudo: false
cache:
  pip: true
  directories:
    - $HOME/.npm
before_install:
  - pip install -U pip setuptools
  - nvm install 6
  - pip install cookiecutter
install:
  - cookiecutter . --no-input
  - pushd json_renderer
  - pip install --upgrade -v .
before_script:
  - |
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
script:
  - ls /home/travis/virtualenv/python3.6.3/share/jupyter/lab/extensions
  - ls /home/travis/virtualenv/python3.6.3/share/jupyter/nbextensions/json_renderer
  - jupyter nbextension enable --py --sys-prefix json_renderer
  - jupyter nbextension list
  - pip install jupyterlab
  - jupyter lab path
  - jupyter labextension list
  - jupyter labextension list 2>&1 | grep -q json_renderer
  - jupyter labextension link
  - popd
