default_context:
    author_name: "{{cookiecutter.author_name}}"
    author_email: "{{cookiecutter.author_email}}"
    mime_type: "{{cookiecutter.mime_type}}"
    file_extension: "{{cookiecutter.file_extension}}"
    mime_short_name: "{{cookiecutter.mime_short_name}}"
    extension_name: "{{cookiecutter.extension_name}}"
